databases:
  - name: satisfactory-planner-db
    plan: free
    databaseName: satisfactory_planner
    user: planner

services:
  - type: web
    name: satisfactory-planner
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npx sequelize-cli db:migrate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: satisfactory-planner-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
